# Generated by Django 4.0.3 on 2022-04-08 08:47

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to=music.models.upload_image_to)),
                ('audio', models.FileField(upload_to=music.models.upload_audio_to)),
                ('type', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
