# Generated by Django 4.0.3 on 2022-04-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_playlist_options_alter_playlist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('user',)},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title',
        ),
    ]
